[package]
name = "risebit/bitframe"
authors = ["Risebit"]
license = "MIT"
description = "BETTER Replacement for TweenService, utilzing 2 different Tweening Type and got many Pre-made Animations & Optimizied."
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/RiseBit/BitFrames"
realm = "shared"

[dependencies]